// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostPublishHandlerFunc turns a function with the right signature into a post publish handler
type PostPublishHandlerFunc func(PostPublishParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostPublishHandlerFunc) Handle(params PostPublishParams) middleware.Responder {
	return fn(params)
}

// PostPublishHandler interface for that can handle valid post publish params
type PostPublishHandler interface {
	Handle(PostPublishParams) middleware.Responder
}

// NewPostPublish creates a new http.Handler for the post publish operation
func NewPostPublish(ctx *middleware.Context, handler PostPublishHandler) *PostPublish {
	return &PostPublish{Context: ctx, Handler: handler}
}

/* PostPublish swagger:route POST /publish postPublish

publish a message to cloud

*/
type PostPublish struct {
	Context *middleware.Context
	Handler PostPublishHandler
}

func (o *PostPublish) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostPublishParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
